config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'homes#index'

  resources :cars, only: %i[index show]
  resources :searches, only: %i[index new create]

  get '/help', to: 'homes#help'
  get '/search', to: 'searches#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/car.rb
class Car < ApplicationRecord
  validates :make, :model, length: { in: 2..50 }, format: {
    with: /[a-zA-Z0-9\-]/,
    message: 'Please, use english letter!'
  }, presence: true
  validates :year, comparison: { greater_than_or_equal_to: 1900, less_than_or_equal_to: Date.current.year },
                   numericality: { only_integer: true }, presence: true
  validates :price, :odometer, numericality: { only_integer: true }, comparison: { greater_than: 0 }, presence: true
  validates :description, length: { maximum: 500 }, presence: true

  scope :filter_by_make, ->(make) { where('make ILIKE ?', make) }
  scope :filter_by_model, ->(model) { where('model ILIKE ?', model) }
  scope :filter_by_year_from, ->(year_from) { where('year >= ?', year_from) }
  scope :filter_by_year_to, ->(year_to) { where('year <= ? ', year_to) }
  scope :filter_by_price_from, ->(price_from) { where('price >= ?', price_from) }
  scope :filter_by_price_to, ->(price_to) { where('price <= ?', price_to) }
  scope :filter_by_order, ->(type, direction) { order(type => direction) }
end

app/models/search.rb
class Search < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :searches, dependent: :delete_all

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  def index
    @cars = FindCar.call(search_params).page params[:page]
  end

  def show
    @car = Car.find(params[:id])
  end

  private

  def search_params
    params.permit(:make, :model, :year_from, :year_to, :price_from, :price_to, :sort_type, :sort_direction, :page)
  end
end

app/controllers/homes_controller.rb
# frozen_string_literal: true

class HomesController < ApplicationController
  def index; end

  def help; end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :authenticate_user!, only: [:index]
  def index
    @user_searches = Search.where(user_id: current_user.id).page params[:page]
  end

  def new
    @search = Search.new
  end

  def create
    @search = Search.create(search_params.merge(user_id: current_user.id)) if current_user
    redirect_to cars_path(search_params)
  end

  private

  def search_params
    params.require(:search).permit(:make, :model, :year_from, :year_to, :price_from, :price_to)
  end
end

app/controllers/users/devise_controller.rb
module Users
  class DeviseController < ApplicationController
    class Responder < ActionController::Responder
      def to_turbo_stream
        controller.render(options.merge(formats: :html))
      rescue ActionView::MissingTemplate => e
        raise e if get?

        if has_errors? && default_action
          render rendering_options.merge(formats: :html, status: :unprocessable_entity)
        else
          redirect_to navigation_location
        end
      end
    end

    self.responder = Responder
    respond_to :html, :turbo_stream
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/cars/index.html.haml
%main
  .container
    %section.py-5
      .row.text-center
        .col-lg-6.col-md-4.mx-auto
          %h1.fw-light List of cars
          %p.lead.text-muted The list is a catalog of cars from around the world and with different parameters. Here you will find exactly what you are looking for!
      %span{:style => "color: #730E15; font-style: italic; font-size: 26px"}
        -unless request.query_parameters.except("sort_direction", "sort_type", "page").blank?
          .card.text-white.bg-primary.mb-3.start-50.translate-middle-x{:style => "max-width: 18rem;"}
            .card-header.text-center Search Request
            .card-body
              %h5.card-text
                Make: #{request.query_parameters[:make]}
                %br
                Model: #{request.query_parameters[:model]}
                %br
                Year from: #{request.query_parameters[:year_from]}
                %br
                Year to: #{request.query_parameters[:year_to]}
                %br
                Price from: #{request.query_parameters[:price_from]}
                %br
                Price to: #{request.query_parameters[:price_to]}
      - if @cars.any?
        %p.text-center.fs-4.fst-italic Number of cars found: #{@cars.total_count}
        .text-center
          = link_to 'Price Asc', cars_path(request.query_parameters.merge({:sort_type => "price"}).merge({:sort_direction => "asc"})), class: "btn btn-outline-primary"
          = link_to 'Price Desc', cars_path(request.query_parameters.merge({:sort_type => "price"}).merge({:sort_direction => "desc"})), class: "btn btn-outline-primary"
          = link_to 'Date Added Asc', cars_path(request.query_parameters.merge({:sort_type => "created_at"}).merge({:sort_direction => "asc"})), class: "btn btn-outline-primary"
          = link_to 'Date Added Desc', cars_path(request.query_parameters.merge({:sort_type => "created_at"}).merge({:sort_direction => "desc"})), class: "btn btn-outline-primary"
        .album.py-5
          .container
            .row.row-cols-1.row-cols-sm-2.row-cols-md-3.g-3
              - @cars.each do |car|
                .col.fs-5
                  .card.shadow-lg.p-2.mb-2.bg-body.rounded.text-center
                    = "Car №#{car.id}"
                  .card-body
                    %p.card-text
                      ="Make: #{car.make}"
                      %br
                      ="Model: #{car.model}"
                      %br
                      ="Year: #{car.year}"
                      %br
                      ="Price: #{car.price}"
                      %br
                      ="Odometer: #{car.odometer}"
                      %br
                      .d-flex.justify-content-between.align-items-center
                        %p.btn-group
                          = link_to 'More', car, class: "btn btn-outline-primary"
                        %small.text-muted
                          = car.created_at.strftime("%Y-%m-%d %H:%M:%S")
      - else
        %section.container
          %p.text-center.fs-4.fst-italic No cars were found for your request.

  =paginate @cars

app/views/cars/show.html.haml
.card.w-50.order-primary.mb-2.start-50.translate-middle-x.search_title.mt-5
  .card-header.fst-italic.fs-4.text-center Car №#{@car.id}
  .card-body
    %h5.card-title #{@car.make + ' ' + @car.model}
    %p.card-text.fs-5
      ="Year: #{@car.year}"
      %br
      ="Odometer: #{@car.odometer}"
      %br
      ="Price: #{@car.price}"
      %br
      ="Description: #{@car.description}"
  .card-footer.bg-transparent.border-success.fs-5.text-center.text-muted
    = @car.created_at.strftime("%Y-%m-%d %H:%M:%S")

app/views/homes/help.html.haml
.container

  %h2.fw-light.text-center Help
  .col-lg-6.col-md-4.mx-auto
    %p.lead.text-muted.text-center Help - here you will find answers to the most frequently asked questions. We hope this helps you :)
  #accordionExample.accordion
    .accordion-item
      %h2#headingOne.accordion-header
        %button.accordion-button.collapsed{"aria-controls" => "collapseOne", "aria-expanded" => "false", "data-bs-target" => "#collapseOne", "data-bs-toggle" => "collapse", :type => "button"}
          How to view all available cars?
      #collapseOne.accordion-collapse.collapse{"aria-labelledby" => "headingOne", "data-bs-parent" => "#accordionExample"}
        .accordion-body
          To view all cars, select the Car List option in the navigation bar.
    .accordion-item
      %h2#headingTwo.accordion-header
        %button.accordion-button.collapsed{"aria-controls" => "collapseTwo", "aria-expanded" => "false", "data-bs-target" => "#collapseTwo", "data-bs-toggle" => "collapse", :type => "button"}
          How to find a car?
      #collapseTwo.accordion-collapse.collapse{"aria-labelledby" => "headingTwo", "data-bs-parent" => "#accordionExample"}
        .accordion-body
          To find a car, select the Search Car option in the navigation bar and fill out the search form.
    .accordion-item
      %h2#headingThree.accordion-header
        %button.accordion-button.collapsed{"aria-controls" => "collapseThree", "aria-expanded" => "false", "data-bs-target" => "#collapseThree", "data-bs-toggle" => "collapse", :type => "button"}
          How to register?
      #collapseThree.accordion-collapse.collapse{"aria-labelledby" => "headingThree", "data-bs-parent" => "#accordionExample"}
        .accordion-body
          To register, open the Account tab and select the Sign up option and fill in the form with data.
    .accordion-item
      %h2#headingFour.accordion-header
        %button.accordion-button.collapsed{"aria-controls" => "collapseThree", "aria-expanded" => "false", "data-bs-target" => "#collapseFour", "data-bs-toggle" => "collapse", :type => "button"}
          How to log in?
      #collapseFour.accordion-collapse.collapse{"aria-labelledby" => "headingFour", "data-bs-parent" => "#accordionExample"}
        .accordion-body
          To log in to your account, open the Account tab and select the Login option. The next step is to enter the data that was specified during registration.
    .accordion-item
      %h2#headingFive.accordion-header
        %button.accordion-button.collapsed{"aria-controls" => "collapseThree", "aria-expanded" => "false", "data-bs-target" => "#collapseFive", "data-bs-toggle" => "collapse", :type => "button"}
          How do I view my search history?
      #collapseFive.accordion-collapse.collapse{"aria-labelledby" => "headingFive", "data-bs-parent" => "#accordionExample"}
        .accordion-body
          To view your search history, select the My Searches option in the navigation bar.
    .accordion-item
      %h2#headingSix.accordion-header
        %button.accordion-button.collapsed{"aria-controls" => "collapseThree", "aria-expanded" => "false", "data-bs-target" => "#collapseSix", "data-bs-toggle" => "collapse", :type => "button"}
          How to logout?
      #collapseSix.accordion-collapse.collapse{"aria-labelledby" => "headingFive", "data-bs-parent" => "#accordionExample"}
        .accordion-body
          To logout to your account, open the Account tab and select the Logout option.

app/views/homes/index.html.haml
%main
  %section.py-5.container
    -if current_user
      %h2.fw-light.fst-italic.text-center.text-primary
        = "Welcome #{current_user.email}!"
    -else
      %h2.fw-light.fst-italic.text-center.text-primary
        = "Welcome to our service!"
      %section.text-center.form
        = link_to 'Login', new_user_session_path, class: "btn btn-outline-primary btn-lg"
        %h5.fw-light.fst-italic.mt-2
          = "Not registered yet? Do it now!"
        = link_to 'Sign up', new_user_registration_path, class: "btn btn-outline-primary  btn-lg"

app/views/layouts/_alerts.html.haml
%p.notice
  = notice
%p.alert
  = alert

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title CarAdvertisementsWeb
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_importmap_tags
  %body
    .container
      %nav.navbar.navbar-expand-lg.navbar-light
        .container-fluid
          = link_to 'Cars Advertisements | Home', root_path, class: "navbar-brand fs-4"
          %button.navbar-toggler{"aria-controls" => "navbarSupportedContent", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-bs-target" => "#navbarSupportedContent", "data-bs-toggle" => "collapse", :type => "button"}
            %span.navbar-toggler-icon
          #navbarSupportedContent.collapse.navbar-collapse
            %ul.navbar-nav.me-auto.mb-2.mb-lg-0.fs-5
              %li.nav-item
                = link_to 'Car List', cars_path, class: "nav-link"
              %li.nav-item
                = link_to 'Search Car', new_search_path, class: "nav-link"
              %li.nav-item
                =link_to "My Searches", searches_path, class: "nav-link"
              %li.nav-item
                = link_to 'Help', help_path, class: "nav-link"
              %li.nav-item.dropdown
                .navbarDropdown.nav-link.dropdown-toggle{"aria-expanded" => "false", "data-bs-toggle" => "dropdown", :href => "#", :role => "button"}
                  Account
                %ul.dropdown-menu{"aria-labelledby" => "navbarDropdown"}
                  - if current_user
                    %li
                      =link_to "Logout", destroy_user_session_path, "data-turbo-method": :delete, class: "dropdown-item"
                  -else
                    %li
                      =link_to "Login", new_user_session_path, class: "dropdown-item"
                    %li
                      =link_to "Sign up", new_user_registration_path, class: "dropdown-item"

    = yield

app/views/searches/_forms.html.haml
.container
  %h3.fw-light.text-center Please enter search rules
  = form_with model: @search, method: :post do |form|
    .row.g-3
      .mt-3
      .col-md-6
        = form.text_field :make, class: "form-control form-control-lg border border-primary border-3 rounded-3 area", placeholder: "Make"
      .col-md-6
        = form.text_field :model, class: "form-control form-control-lg border border-primary border-3 rounded-3 area", placeholder: "Model"
    .row.justify-content-md-center
      .mt-3
      .col-md-6
        = form.number_field :year_from, class: "form-control form-control-lg border border-primary border-3 rounded-3 area", placeholder: "Year from"
      .col-md-6
        = form.number_field :year_to, class: "form-control form-control-lg border border-primary border-3 rounded-3 area", placeholder: "Year to"
    .row.justify-content-md-center
      .mt-3
      .col-md-6
        = form.number_field :price_from, class: "form-control form-control-lg border border-primary border-3 rounded-3 area", placeholder: "Price from"
      .col-md-6
        = form.number_field :price_to, class: "form-control form-control-lg border border-primary border-3 rounded-3 area", placeholder: "Price to"
      %div.text-center
        = form.submit "Search", class: "btn btn-outline-primary btn-lg search_form"

app/views/searches/index.html.haml
%div
  - if @user_searches.any?
    %h3.text-center.fs-4.fst-italic Searches #{current_user.email}
    .album.py-5
      .container
        .row.row-cols-1.row-cols-sm-2.row-cols-md-3.g-3
          - @user_searches.each do |search|
            .col.fs-5
              .card.shadow-lg.p-2.mb-2.bg-body.rounded.text-center
                = "Search №#{search.id}"
              .card-body
                %p.card-text
                  ="Make: #{search.make}"
                  %br
                  ="Model: #{search.model}"
                  %br
                  ="Year from: #{search.year_from}"
                  %br
                  ="Year to: #{search.year_to}"
                  %br
                  ="Price from: #{search.price_from}"
                  %br
                  ="Price to: #{search.price_to}"
                  %br
                  .d-flex.justify-content-between.flex-row-reverse
                    %small.text-muted
                      = search.created_at.strftime("%Y-%m-%d %H:%M:%S")
    .album.py-5
  - else
    .text-center.form.fs-4
      = "You haven't searched yet. Want to do?"
      %br.btn-group
        = link_to 'Search', new_search_path, class: "btn btn-outline-primary"
= paginate @user_searches

app/views/searches/new.html.haml
= render "forms"